# This file was generated by GoReleaser. DO NOT EDIT.
cask "db-migrator" do
  version "1.8.2"

  on_macos do
    on_intel do
      sha256 "73088f00bce8aec218b04f248e9796aecda81e48d6f19179af93bc1b69957d70"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6cda71b265a0bd12ae3b08fb87489126c56235642e6fcef2ec35e47814e35fd8"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "64f0de1e4cd78d6ee3c4fc03e1f25c16b8b786c091bb98bf7281bf8ca22b2f35"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1caa34b666cfef487d46c9e8641cc862d971eec121b1ade4d2b3e241abb3eb20"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "db-migrator"
  desc "CLI tool for managing database migrations (ClickHouse, PostgreSQL, MySQL, Tarantool, Iceberg)."
  homepage "https://github.com/raoptimus/db-migrator.go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "db-migrator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/db-migrator"]
    end
  end

  # No zap stanza required

end
