# This file was generated by GoReleaser. DO NOT EDIT.
cask "db-migrator" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "c8dd099ecc685c503467506cecfc4d5377d5da2e25b31662c8bdeb1ba70b8b58"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "394a6b1cb066e6bfeff778d159e0fc68dd9da39220fe54168691380639a7727b"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9c3cff19555e625995aaa8259b6d4bde73b187a6640b24d08706fae51c355ce"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0923bf514305f5c645cdad66b6210f889936de8831e18bfae34351e637af7d0f"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "db-migrator"
  desc "CLI tool for managing database migrations (ClickHouse, PostgreSQL, MySQL, Tarantool, Iceberg)."
  homepage "https://github.com/raoptimus/db-migrator.go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "db-migrator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/db-migrator"]
    end
  end

  # No zap stanza required

end
