# This file was generated by GoReleaser. DO NOT EDIT.
cask "db-migrator" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "e8ba7ba0c23ac749405e2ff0228e262b1f78033bdd67b3af010ac35d226fd289"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4e43dbb1a0a229b24e8479ec76746034d90cd10858d65248641bfe4db1c746db"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c12ef4b7a55750f08fe23ad8340d7ec9548a10e5165d3012925b9d529cc2cc8"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "89aacaa70cb6fdccff3b9218d9ed7e18a4cfe86e6473d69422c54aefc85a1e69"
      url "https://github.com/raoptimus/db-migrator.go/releases/download/v#{version}/db-migrator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "db-migrator"
  desc "CLI tool for managing database migrations (ClickHouse, PostgreSQL, MySQL, Tarantool, Iceberg)."
  homepage "https://github.com/raoptimus/db-migrator.go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "db-migrator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/db-migrator"]
    end
  end

  # No zap stanza required

end
